name: Branch Filtered Workflow

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  branch-check:
    runs-on: ubuntu-latest
    env:
      ALLOWED_BRANCHES: ${{ vars.ALLOWED_BRANCHES }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine branch
        id: branch
        run: |
          echo "ref: $GITHUB_REF"
          # Get actual branch name for push or PR
          if [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            BRANCH="${GITHUB_REF#refs/heads/}"
          #cheching if it is pull request and accordingly pulling the branch name
          elif [[ "${GITHUB_REF}" == refs/pull/* ]]; then
            BRANCH="${GITHUB_HEAD_REF}"
          else
            echo "Unknown ref format: $GITHUB_REF"
            exit 1
          fi
          #setting env named "CURRENT_BRANCH"
          echo "CURRENT_BRANCH=$BRANCH" >> $GITHUB_ENV  

      - name: Check if current branch is allowed
        id: check
        run: |
          echo "Allowed branches: $ALLOWED_BRANCHES"
          echo "Current branch: $CURRENT_BRANCH"
          #setting up varibale run-pipeline to false
          RUN_PIPELINE=false
          # checking the allowed branches and making the variable true for further pipeline running
          for pattern in $ALLOWED_BRANCHES; do
            if [[ "$CURRENT_BRANCH" == $pattern ]]; then
              RUN_PIPELINE=true
              break
            fi
            # Handle wildcard pattern (feature/*, release/*)
            if [[ "$pattern" == *"*"* ]]; then
              if [[ "$CURRENT_BRANCH" == $pattern ]]; then
                RUN_PIPELINE=true
                break
              fi
            fi
          done
          echo "RUN_PIPELINE=$RUN_PIPELINE" >> $GITHUB_ENV

      - name: Run only if branch is allowed
        if: env.RUN_PIPELINE == 'true'
        run: echo "✅ Allowed branch '$CURRENT_BRANCH' — running pipeline!"

      - name: Skip message if branch not allowed
        if: env.RUN_PIPELINE != 'true'
        run: echo "❌ Branch '$CURRENT_BRANCH' not allowed — skipping logic."
