name: Hello World Workflow

on:
  push:
    branches:
      - "*"  
  pull_request:
    branches:
      - "*"  

jobs:
  build:
    name: api-ci
    runs-on: ubuntu-latest

    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show event and branch
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Ref Name: ${{ github.ref_name }}"
          echo "Full Ref: ${{ github.ref }}"

      - name: Say Hello
        run: echo "Hello World - pipeline is running!"
